urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
import settings

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'shit.views.index'),
    url(r'^(?P<shit_id>\d+)$', 'shit.views.shit_short_redirect'),
    (r'^shit/', include('shit.urls', namespace='shit', app_name='shit')),
    (r'^twitter/', include('twitter.urls', namespace='twitter', app_name='twitter')),
    (r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns('django.views',
        url(r'^'+settings.MEDIA_URL[1:]+'(.*)$',
            'static.serve',
            dict(document_root=settings.MEDIA_ROOT)
        ),
    )

apps/shit/forms.py
from django.forms import ModelForm
import models as M

class ShitHappens(ModelForm):
    class Meta:
        model = M.Shit
        exclude = ('slug', 'user')

class Comment(ModelForm):
    class Meta:
        model = M.Comment
        include = ('text', )
        exclude = ('shit', 'user')

class Review(ModelForm):
    class Meta:
        model = M.Review
        exclude = ('datetime', 'user')

class Image(ModelForm):
    class Meta:
        model = M.Image
        include = ('pic', )
        exclude = ('datetime', 'user')

templates/widgets/comments.html
{% load comment_tags %}

{% if comments %}
     <h3> Comments </h3>
{% endif %}
<div id="comments">
{% for comment in comments %}
{% if comment.datetime >= visit_datetime %}
  <p class="comment highlight" id="comment{{comment.id}}"
{% else %}
  <p class="comment" id="comment{{comment.id}}"
{% endif %}
     onmouseover="show_links(this);"
     onmouseout="hide_links(this);">
  
    <a class="comment-link" href="{{ request.path }}#comment{{ comment.id }}">
      link
    </a>
    {% if request.user != comment.user %}
  <a href="#comment-form" class="comment-link"
      onclick="javascript:reply_to('{{ comment.user }}')">
      @reply
    </a>
    {% endif %}
    <a class="comment-author" href="{% url shit:usershit user=comment.user %}">{{comment.user}}</a>
    {{ comment|linebreaksbr|users_highlight}}
</p>
{% if not forloop.last %}
<div class="hr">&nbsp;</div>
{% endif %}

{% endfor %}
</div>

templates/widgets/countdown.html
<script language="JavaScript">
TargetDate = "{{ shitday.get_next_shit_utc }}";
CountActive = true;
CountStepper = -1;
LeadingZero = true;
DisplayFormat = "@{{ usershit }}<br /> get ready for shit in <br />%%D%% Days %%H%%:%%M%%:%%S%%";
FinishMessage = "@{{ usershit }} be ready!<br />Shit Is Here!";
</script>
<script language="JavaScript" src="/static/countdown.js"></script>

templates/widgets/entry.html
{% load shit_tags %}

<div class="hentry">
    <abbr class="updated">
        {{ shit.datetime|date:"Y-m-d" }}
    </abbr>
    <h3>
        <a href="{% url shit:shit user=shit.user.username slug=shit.slug %}"> {{ shit.header }} </a>
    </h3>

    <ul class="tags">
        <li>
            <a href="{% url shit:usershit user=shit.user.username %}" rel="tag">@{{ shit.user }}</a>
        </li>
        <li>
            <a href="{% url shit:shit user=shit.user.username slug=shit.slug %}#comments" rel="tag" >Comments: {{ shit.comment_set.count }}</a>
        </li>

    </ul>


    <div class="entry-content">
         {{ shit.description|rst2html}}
    </div>

</div>

templates/widgets/small_entry.html
<div class="hentry">
    <abbr class="updated">
        {{ shit.datetime|date:"Y-m-d" }}
    </abbr>
    <h3>
         <a href="{% url shit:shit user=shit.user.username slug=shit.slug %}" rel="bookmark">{{ shit.header }}</a>
    </h3>
</div>