apps/shit/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('shit.views',
    url(r'^about/$', 'about', name='about'),
    url(r'^happens/$', 'shithappens', name='shithappens'),
    url(r'^happens/submit/$', 'shithappens_submit', name='shithappens_submit'),
    url(r'^review/$', 'review', name='review'),
    url(r'^review/submit/$', 'review_submit', name='review_submit'),
    url(r'^pic/add/', 'pic_add', name='pic_add'),
    url(r'^pic/form/', 'pic_form', name='pic_form'),
    url(r'^(?P<user>.+)/(?P<slug>.+)/$', 'shit', name='shit'),
    url(r'^(?P<user>.+)/(?P<slug>.+)/comment$', 'comment', name='comment'),
    url(r'^(?P<user>.+)/$', 'usershit', name='usershit'),
)

urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
import settings

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'shit.views.index'),
    url(r'^(?P<shit_id>\d+)$', 'shit.views.shit_short_redirect'),
    (r'^shit/', include('shit.urls', namespace='shit', app_name='shit')),
    (r'^twitter/', include('twitter.urls', namespace='twitter', app_name='twitter')),
    (r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns('django.views',
        url(r'^'+settings.MEDIA_URL[1:]+'(.*)$',
            'static.serve',
            dict(document_root=settings.MEDIA_ROOT)
        ),
    )

apps/shit/models.py
from django.contrib import admin
from django.contrib.auth.models import User
from django.db import models

import datetime as dt

class Shit(models.Model):
    header = models.CharField(max_length=200)
    description = models.TextField()
    datetime = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User)
    slug = models.SlugField()

    class Meta:
        unique_together = (('user', 'slug'), )
        ordering = ('-datetime', )

    def __unicode__(self):
        return self.header

class Comment(models.Model):
    shit = models.ForeignKey(Shit)
    user = models.ForeignKey(User)
    text = models.TextField()
    datetime = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ('datetime', )
        
    def __unicode__(self):
        return self.text
    
class Visit(models.Model):
    shit = models.ForeignKey(Shit)
    user = models.ForeignKey(User)
    datetime = models.DateTimeField(auto_now_add=True)
    
    def update_now(self):
        self.datetime = dt.datetime.now()
        self.save()

class ShitDay(models.Model):
    user = models.ForeignKey(User)
    floated_timedelta = models.FloatField()
    next_shit = models.DateTimeField()

    def get_timedelta(self):
        return dt.timedelta(self.floated_timedelta)

    def set_timedelta(self, timedelta):
        self.floated_timedelta = timedelta.days + timedelta.seconds/86400.

    def get_next_shit_utc(self):
        return self.next_shit.strftime('%m/%d/%Y %I:%M %p %z')

    def __unicode__(self):
        return self.user
        
class Review(models.Model):
    user = models.ForeignKey(User)
    opinion = models.TextField()
    datetime = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return '%s: %s'%(self.user, self.opinion[:80])

HINTS = (
    (u'comment', u'You can comment on a message using the form below.'),
    (u'reply', u'You can reply to user using "reply" link, also you can reply to twitter.'),
    (u'shithappens', u'If things are bad you can share with your friends by clicking the "Shit Happens" button.'),
)

class HintDelivery(models.Model):
    user = models.ForeignKey(User)
    hint = models.CharField(max_length=50, choices=HINTS)

    @classmethod
    def deliver(cls, request, label):
        hint_display = None
        for hint_label, hint in HINTS:
            if label==hint_label:
                hint_display = hint
                break
        if not hint_display:
            raise NameError, "Hint label \"%s\" not found"%label

        if request.user.is_authenticated():
            hint, created  = cls.objects.get_or_create(user=request.user, hint=label)
            if created:
                return hint_display
            else:
                return None
        else:
            if request.session.get('hint_%s'%label):
                return None
            else:
                request.session['hint_%s'%label] = True
                return hint_display

    def __unicode__(self):
        return self.hint

class Image(models.Model):
    user = models.ForeignKey(User)
    datetime = models.DateTimeField(auto_now_add=True)
    pic = models.ImageField(upload_to="uploaded_pics")

    def __unicode__(self):
        return u"Pic: <%s> at %s"%(self.user, self.datetime)
    
class ShitAdmin(admin.ModelAdmin):
    pass

class CommentAdmin(admin.ModelAdmin):
    pass

class ReviewAdmin(admin.ModelAdmin):
    pass

class ImageAdmin(admin.ModelAdmin):
    pass

admin.site.register(Shit, ShitAdmin)
admin.site.register(Comment, CommentAdmin)
admin.site.register(Review, ReviewAdmin)
admin.site.register(Image, ImageAdmin)

apps/shit/forms.py
from django.forms import ModelForm
import models as M

class ShitHappens(ModelForm):
    class Meta:
        model = M.Shit
        exclude = ('slug', 'user')

class Comment(ModelForm):
    class Meta:
        model = M.Comment
        include = ('text', )
        exclude = ('shit', 'user')

class Review(ModelForm):
    class Meta:
        model = M.Review
        exclude = ('datetime', 'user')

class Image(ModelForm):
    class Meta:
        model = M.Image
        include = ('pic', )
        exclude = ('datetime', 'user')

apps/shit/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from django.contrib import messages
from django.core.mail import mail_admins
from django.core.urlresolvers import reverse
from django.db import IntegrityError
from django.db.models import Count
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render_to_response
from django.shortcuts import get_object_or_404
from django.template import Context
from django.template import RequestContext
from django.template.loader import get_template

import settings
import forms as F
import models as M

from pytils.translit import slugify
from tweepy import TweepError
import urlparse
import datetime

def index(request):
    shits = M.Shit.objects.annotate(Count('comment')).order_by('-datetime', '-comment__count', 'header')
    messages.info(request, M.HintDelivery.deliver(request, u'shithappens'))
    context = RequestContext(request, {'shits':shits})
    return render_to_response('index.html', context)

def shit(request, user, slug):
    user = get_object_or_404(User, username=user)
    shit = get_object_or_404(M.Shit, user=user, slug=slug)
    form = F.Comment()
    comments = M.Comment.objects.filter(shit=shit).all()
    if request.user.is_authenticated():
        visit, created = M.Visit.objects.get_or_create(user=request.user, shit=shit)
        visit_datetime = visit.datetime
        new_comments = comments.filter(datetime__gte=visit_datetime).count()
        visit.update_now()
    else:
        visit_datetime = new_comments = None
    try:
        shitday = M.ShitDay.objects.get(user=user)
    except M.ShitDay.DoesNotExist:
        shitday = None
        
    hint = M.HintDelivery.deliver(request, u'comment') or \
           M.HintDelivery.deliver(request, u'reply')
    messages.info(request, hint)
    context = RequestContext(request, {'comments':comments, 'shit':shit, 'form':form, \
        'usershit':user, 'visit_datetime':visit_datetime, 'new_comments':new_comments, \
        'shitday':shitday})
    return render_to_response('shit/shit.html', context)

def shit_short_redirect(request, shit_id):
    shit = get_object_or_404(M.Shit, id=shit_id)
    path = reverse('shit:shit', \
        kwargs={'user':shit.user.username, 'slug':shit.slug})
    path = 'http://journalofshit.ru%s'%path
    return HttpResponseRedirect(path)

def usershit(request, user):
    user = get_object_or_404(User, username=user)
    shits = M.Shit.objects.filter(user=user)
    try:
        shitday = M.ShitDay.objects.get(user=user)
    except M.ShitDay.DoesNotExist:
        shitday = None
    context = RequestContext(request, {'shits':shits, 'shitday':shitday, 
        'usershit':user})
    return render_to_response('shit/usershit.html', context)

def comment(request, user, slug):
    user = get_object_or_404(User, username=user)
    shit = get_object_or_404(M.Shit, user=user, slug=slug)
    form = F.Comment(request.POST)
    if form.is_valid():
        if request.user.is_authenticated():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.shit = shit
            comment.save()
            messages.info(request, 'Thank you for your vote.')
            visit, created = M.Visit.objects.get_or_create(user=request.user, shit=shit)
            visit.update_now()
            if request.POST.get('twitter'):
                api = bitly.Api(login='mylokin', apikey='R_f6000ab74f4a8bdc0fa553761c4a63f8')
                path = reverse('shit:shit', kwargs={'user':request.user.username, \
                    'slug':comment.shit.slug})
                link = api.shorten(absurl(path))
                message = "%s %s"%(cut(comment.text, 120-len(link)), link)
                try:
                    request.user.twitter.api.update_status(message)
                except:
                    pass
            return HttpResponseRedirect(reverse('shit:shit', \
                kwargs={'user':user.username, 'slug':shit.slug}))
        else:
            request.session['twitter_post_data'] = dict(form.cleaned_data)
            return HttpResponseRedirect("%s?next=%s"%(settings.LOGIN_URL, request.path))
    else:
        comments = M.Comment.objects.filter(shit=shit).all()
        context = RequestContext(request, {'comments':comments, 'shit':shit, 'form':form})
        return render_to_response('shit/shit.html', context)
        


@login_required
def shithappens(request):
    usershit = request.user
    context = RequestContext(request, {'form':F.ShitHappens(), \
        'usershit':usershit})
    return render_to_response('shit/shithappens.html', context)

@login_required
def shithappens_submit(request):
    form = F.ShitHappens(request.POST)
    if form.is_valid():
        shit = form.save(commit=False)
        shit.user = request.user
        shit.slug = slugify(shit.header)
        path = reverse('shit:shit', kwargs={'user':request.user.username, 'slug':shit.slug})
        try:
            shit.save()
        except IntegrityError:
            messages.error(request, 'You have already talked about this here.')
        else:
            if request.POST.get('twitter'):
                link = 'http://jos.su/%s'%shit.id
                message = "#journalofshit %s %s"%(cut(shit.header, 120-len(link)), link)
                try:
                    request.user.twitter.api.update_status(message)
                except TweepError:
                    pass
                except:
                    pass
            usershit = M.Shit.objects.filter(user=request.user).order_by('-datetime')
            if usershit.count()>1:
                current_timedelta = usershit[0].datetime - usershit[1].datetime
                try:
                    shitday = M.ShitDay.objects.get(user=request.user)
                except M.ShitDay.DoesNotExist:
                    shitday = M.ShitDay()
                    shitday.user = request.user
                    shitday.set_timedelta(current_timedelta)
                    shitday.next_shit = datetime.datetime.now() + current_timedelta
                    shitday.save()
                else:
                    usershit_counter = usershit.count()
                    new_timedelta = (current_timedelta + shitday.get_timedelta()*(usershit_counter-1))
                    new_timedelta/=usershit_counter
                    shitday.set_timedelta(new_timedelta)
                    shitday.next_shit = datetime.datetime.now() + new_timedelta
                    shitday.save()
        return HttpResponseRedirect(path)
    else:
        context = RequestContext(request, {'form':form})
        return render_to_response('shit/shithappens.html', context)

def about(request):
    context = RequestContext(request)
    return render_to_response('shit/about.html', context)

@login_required
def review(request):
    usershit = request.user
    context = RequestContext(request, {'form':F.Review(), \
        'usershit':usershit})
    return render_to_response('shit/review.html', context)

@login_required
def review_submit(request):
    form = F.Review(request.POST)
    if form.is_valid():
        review = form.save(commit=False)
        review.user = request.user
        review.save()
        if settings.EMAIL_HOST:
            mail_admins(u'Review from %s'%review.user, review.opinion)
        context = RequestContext(request)
        return render_to_response('shit/review_thanks.html', context)
    else:
        context = RequestContext(request, {'form':form})
        return render_to_response('shit/review.html', context)

@login_required
def pic_add(request):
    if request.method=="POST":
        form = F.Image(request.POST, request.FILES)
        if form.is_valid():
            image = form.save(commit=False)
            image.user = request.user
            image.save()
            status = True if image else False
        else:
            status = False
        return render_to_response('shit/addpic.html', {'status':status})
    else:
        return HttpResponseForbidden("Forbidden")

@login_required
def pic_form(request):
    form = F.Image()
    context = RequestContext(request, {'form':form})
    return render_to_response('shit/addpicform.html', context)


def cut(string, length):
    length = int(length)
    gen = (word for word in string.split())
    string = gen.next()
    if len(string)>length:
        return '%s...'%string[:length]
    for word in gen:
        if len('%s %s'%(string, word))>length:
            return '%s...'%string
        else:
            string = '%s %s'%(string, word)
    return string

def absurl(path):
    domain = "http://journalofshit.ru" #TODO site bugfix
    return urlparse.urljoin(domain, path)    

def format_timedelta(timedelta):
    return str(timedelta).split('.', 2)[0]

def get_notification(user, filename, repeate=False, **kwargs):
    '''
    notification = get_notification(request.user, 'notification/new_comments.html', \
        new_comments_count=3)
    '''
    notification, created = M.NotificationDelivery.objects.get_or_create(user=user)
    if repeate or created:
        context = Context(kwargs)
        template = get_template(filename)
        return template.render(context)
    else:
        return None

templates/shit/about.html
{% extends 'base.html' %}

{% block content %}

<h3> Добро пожаловать! </h3>
<p> Journal of shit - это место, где вы сполна можете выразить свой
гнев и обсудить с друзьями, насколько все действительно плохо. </p>

<h4> Вход </h4>
<p> Вход на сайт осуществляется посредством социальной сети twitter. </p>

<h4> Сообщения </h4>
<p> Сообщения, создаваемые пользователями, могут быть опубликованны в
вашем twitter'е. Что позволит вашим друзьям принять участие в
обсуждении. </p>

<h4> Поиск сообщений </h4>
<p> Поиск сообщений происходит благодаря любым поисковым системам
поддерживающим twitter. Для поиска последних сообщений вам стоит
использовать поисковый запрос содержащий хэштег #journalofshit. </p>
{% endblock %}

templates/shit/addpic.html
{{ status }}

templates/shit/addpicform.html
<form id="upload_form" action="{% url shit:pic_add %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <span>Chose picture you want to upload</span> {{ form.pic }}
  <br />
 <input type="submit" />
</form>

templates/shit/review.html
{% extends 'base.html' %}

{% block extra_head %}
    <link rel='stylesheet' type='text/css' href='{{ MEDIA_URL }}form.css'>
{% endblock %}

{% block content %}
<form action="{% url shit:review_submit %}" method="post">
{% csrf_token %}
<table>
    <tr>
        <th>
            Your opinion about service
        </th>
        <td>
	    {{ form.opinion.errors }}
            {{ form.opinion }}
        </td>
    </tr>

    <tr>
        <td colspan=2 class="submit">
            <input type="Submit" value="Post" />
        </td>
    </tr>

</table>
</form>
{% endblock %}

templates/shit/review_thanks.html
{% extends 'base.html' %}

{% block content %}
<h3> Спасибо за ваше мнение!</h3>
<p> Ваш отзыв будет обязательно учтен при дальнейшей разработке сайта.</p>
{% endblock %}

templates/shit/shit.html
{% extends 'base.html' %}

{% block extra_head %}
    <link rel='stylesheet' type='text/css' href='{{ MEDIA_URL }}form.css'>
    <script language="javascript" src="{{ MEDIA_URL }}comment.js"></script>
    <script>
    $('#id_text').change(function(){
      if($('#id_text').val().match(/@\w+ .+/gim)){
        alert($('label'));
      }else{
        alert('fsd');
      };
    });
    </script>

{% endblock %}

{% block content %}
   {% include 'widgets/entry.html' %}
   {% include 'widgets/comments.html' %}
   <form id="comment-form" name="comment" action="{% url shit:comment user=shit.user slug=shit.slug %}" method="post">
   {% csrf_token %}
   <table>
   
      <tr>
         <th>
            Comment
         </th>
         <td>
            <ul>
               {{ form.text.errors }}
            </ul>
            <textarea name="text" id="id_text"></textarea>
         </td>
      </tr>
      <tr>
	<th colspan=2> <span id="action_label">Post to twitter</span>
	  <input id="twitter" class="checkbox" type="checkbox" name="twitter" />
	</th>
      </tr>
      <tr>
         <td colspan="2" class="submit">
            <input type="submit" value="Post" />
         </td>
      </tr>

   </table>
   
   </form>
{% endblock %}

{% block extra_menu %}
   <a href="#comments">Comments
       {% if new_comments %}
       <strong>{{ new_comments }}</strong>
       {% endif %}
   </a>
{% if shitday %}
<small><strong>
{% include 'widgets/countdown.html' %}
</strong></small>
{% endif %}
{% endblock %}

templates/shit/shithappens.html
{% extends 'base.html' %}

{% block extra_head %}
    <link rel='stylesheet' type='text/css' href='{{ MEDIA_URL }}form.css'>
    <link rel='stylesheet' type='text/css' href='{{ MEDIA_URL }}facebox/facebox.css'>

<script type="text/javascript">
$(document).ready(function(){
    $('a[rel*=facebox]').facebox()
})
</script>  
{% endblock %}

{% block content %}
<form action="{% url shit:shithappens_submit %}" method="post">
{% csrf_token %}
<table>
    <tr>
        <th>
            What happens?
        </th>
        <td>
	    {{ form.header.errors }}
            {{ form.header }}
        </td>
    </tr>

    <tr>
        <th>
            Describe situation
        </th>
        <td>
	    {{ form.description.errors }}
            {{ form.description }}
        </td>
    </tr>
    
    <tr>
        <th colspan="2">
	    <a href="{% url shit:pic_form %}" rel="facebox"> 
	        Upload Image
            </a>
	</th>
    </tr>

    <tr>
        <th colspan=2> Post to twitter
	  <input class="checkbox" type="checkbox" checked name="twitter" />
	</th>
    </tr>
    <tr>
        <td colspan=2 class="submit">
            <input type="Submit" value="Shit Happens!" />
        </td>
    </tr>

</table>
</form>
{% endblock %}

templates/shit/usershit.html
{% extends 'base.html' %}

{% block extra_menu %}
{% if shitday %}
<small><strong>
{% include 'widgets/countdown.html' %}
</strong></small>
{% endif %}
{% endblock %}

{% block content %}

{% for shit in shits %}
{% if forloop.first %}
    {% include 'widgets/entry.html' %}
{% else %}
    {% include 'widgets/small_entry.html' %}
{% endif %}
{% endfor %}

{% endblock %}